# Generated by Django 5.0.2 on 2025-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_type', models.CharField(choices=[('objects', 'Объекты'), ('cad_del', 'Кадастровые деления'), ('admin_del', 'Административные деления'), ('zouit', 'ЗОУИТ'), ('ter_zone', 'Территориальные зоны')], max_length=20)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type'], name='maps_search_object__ec127b_idx'), models.Index(fields=['name'], name='maps_search_name_0ec11b_idx')],
            },
        ),
    ]
