services:
  - type: web
    name: mgis-ogd-backend
    env: python
    rootDir: .
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python backend/manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://YOUR_USERNAME.github.io" 