services:
  - type: web
    name: mgis-ogd-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      PYTHONPATH=$PYTHONPATH:/opt/render/project/src python manage.py collectstatic --noinput
    startCommand: PYTHONPATH=$PYTHONPATH:/opt/render/project/src gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: "django-insecure-render-production-secret-key-2024"
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://dimenicetry.github.io/MGIS-OGD/"
      - key: PYTHONPATH
        value: "/opt/render/project/src" 