services:
  - type: web
    name: mgis-ogd-backend
    env: python
    rootDir: .
    buildCommand: chmod +x build.sh && ./build.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://dimenicetry.github.io/MGIS-OGD/" 